---
- name: Create subdomain static dirs
  ansible.builtin.file:
    state: directory
    mode: '0755'
    owner: "{{ __galaxy_privsep_user_name }}"
    group: "{{ __galaxy_privsep_user_group }}"
    path: "{{ galaxy_themes_static_path }}/static-{{ subdomain.name }}"

- name: Add generic static files to subdomain static dir
  ansible.builtin.unarchive:
    src: "{{ galaxy_themes_static_path }}/static.gz"
    dest: "{{ galaxy_themes_static_path }}/static-{{ subdomain.name }}"
    remote_src: yes

- name: Check if welcome.html is present in files
  ansible.builtin.stat:
    path: "{{ galaxy_themes_ansible_file_path }}/{{ subdomain.name }}/static/welcome.html"
  register: custom_welcome

- name: Create welcome.html directory
  ansible.builtin.file:
    state: directory
    mode: '0755'
    owner: "{{ __galaxy_privsep_user_name }}"
    group: "{{ __galaxy_privsep_user_group }}"
    path: "{{ galaxy_themes_static_path }}/static-{{ subdomain.name }}/welcome.html"

- name: Check if iframe for subdomain exists
  ansible.builtin.uri:
    url: "{{ galaxy_themes_welcome_url_prefix }}{{ subdomain.name }}.html"
    return_content: true
  register: iframe
  failed_when: false
  when: not custom_welcome.stat.exists

- name: Template welcome.html for subdomains
  ansible.builtin.template:
    src: welcome.html.j2
    dest: "{{ galaxy_themes_static_path }}/static-{{ subdomain.name }}/welcome.html/index.html"
    owner: "{{ __galaxy_privsep_user_name }}"
    group: "{{ __galaxy_privsep_user_group }}"
    mode: '0644'
  when: not custom_welcome.stat.exists

- name: Copy static files
  ansible.builtin.include_tasks: copy_static_files.yml
  loop: "{{ galaxy_themes_static_keys | dict2items }}"
  loop_control:
    loop_var: object
